/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.rutgers.main;

public class SongLib {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new SongLib().getGreeting());
    }
}
